title: "Introduction to Differential Manifolds"
code: MATH670
year: 2025
institution: "Colorado State University"
author: Clayton Shonkwiler
structure: 
    - type: standalone
      title: Notes
      source: dg.tex
build_pdf: true
